name: Go

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x # Replace with the desired Go version

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: go build

      - name: Test
        run: go test ./...

