name: go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          go build ./...
          go test ./...

      - name: Build and run HTTP server
        working-directory: ./http
        run: |
          go build -o http-server .
          ./http

      - name: Build and run RPC server
        working-directory: ./rpc
        run: |
          go build -o rpc-server .
          ./rpc
