version: '3'
services:
  http-server:
    build:
      context: ./http-server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - rpc-server

  rpc-server:
    build:
      context: ./rpc-server
      dockerfile: Dockerfile
    ports:
      - 50051:50051
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=tiktok@#123
      - MYSQL_DATABASE=Assignment_Database
    ports:
      - 3306:3306
