version: '3'
services:
  http-server:
    build:
      context: ./http
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rpc-server

  rpc-server:
    build:
      context: ./rpc
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
